# Default values.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

name: cma-operator
image:
   repo: quay.io/samsung_cnct/cma-operator:0.1.9
cma:
   enabled: false
   endpoint: cma-grpc.cnct.io:443
   insecure: false
   apiProxyEndpoint: proxy.uswest1.cnct.io
   apiProxyTls: cma-api-proxy-tls

